pull_request_rules:
  - name: automatic merge for master when CI passes
    conditions:
      - status-success=Travis CI - Pull Request
      - label=ready-to-merge
      - base=master
    actions:
      merge:
        method: merge
