pull_request_rules:
  - name: automatic merge
    conditions:
      - status-success=Travis CI - Pull Request
      - label=ready-to-merge
      - label=!squash-merge
      - base=master
    actions:
      merge:
        method: merge
  - name: automatic squash merge
    conditions:
      - status-success=Travis CI - Pull Request
      - label=ready-to-merge
      - label=squash-merge
      - base=master
    actions:
      merge:
        method: squash
  - name: branch deletion after merge
    conditions:
      - merged
      - label=delete-branch
    actions:
      delete_head_branch: {}
