pull_request_rules:
  - name: Automatic merge on approval and CI pass
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
    base: master
    actions:
      merge:
        method: merge
