language: generic

matrix:
  include:
    - os: linux
      dist: bionic
      env: BADGE=bionic
    - os: linux
      dist: focal
      env: BADGE=focal

branches:
  only:
  - master

compiler:
- gcc

before_install:
- ./.ci/ci_before_install.sh

before_script: 

script:
