language: generic
jobs:
  os:
  - linux
    dist: bionic
  - linux
    dist: focal
branches:
  only:
  - master
sudo: required
compiler:
- gcc
before_install:
- ./.ci/ci_before_install.sh
before_script: 
script:
