language: generic
os:
  - linux
matrix:
  include:
    - dist: bionic
    - dist: focal
branches:
  only:
  - master
sudo: required
compiler:
- gcc
before_install:
- ./.ci/ci_before_install.sh
before_script: 
script:
