language: generic
os:
  - linux
env:
  - BADGE=bionic
  - BADGE=focal
jobs:
  include:
    - env: BADGE=bionic
      dist: bionic
    - env: BADGE=focal
      dist: focal
branches:
  only:
  - master
compiler:
- gcc
before_install:
- ./.ci/ci_before_install.sh
before_script: 
script:
