language: generic

os:
  - linux

env:
  - BADGE=bionic
  - BADGE=focal

dist:
  - bionic
  - focal

matrix:
  exclude:
    - dist: bionic
      env: BADGE=focal
    - dist: focal
      env: BADGE=bionic

branches:
  only:
  - master

compiler:
- gcc

before_install:
- ./.ci/ci_before_install.sh

before_script: 

script:
