language: generic
os:
  - linux
env:
  - BADGE=bionic
  - BADGE=focal
dist:
  - bionic
  - focal
jobs:
  exclude:
    - env: BADGE=bionic
      dist: focal
    - env: BADGE=focal
      dist: bionic
branches:
  only:
  - master
compiler:
- gcc
before_install:
- ./.ci/ci_before_install.sh
before_script: 
script:
