# backend
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
vsync = true;
dbe = false;
paint-on-overlay = true;
unredir-if-possible = false;
use-damage = true;

# opacity
opacity-rule=[ 
  "94:class_g = 'URxvt'",
  "100:class_g = 'i3bar'"
];

# fading
fading = true;
fade-in-step = 0.035; # larger number for faster fading
fade-out-step = 0.035;

# fancy blur 
blur-background = true;
blur-method = "dual_kawase"; 
blur-strength = 7;
