# backend
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
vsync = true;
dbe = false;
paint-on-overlay = true;
unredir-if-possible = false;
use-damage = true;

# fading
fading = false;
