#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent%";

# $timeleft=`upower -i $(upower -e | grep -i 'bat') | grep "time to empty" | vims -s "df:^dtW"`

if ($status eq 'Discharging') {
	$full_text .= ' DIS';
} elsif ($status eq 'Charging') {
	$full_text .= ' CHR';
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

# default dark colors
# EPIGEN_DEL_BLOCK_COLORSCHEME_LIGHT {

	if ($percent < 20) {
		print "#ff6666\n";
	} elsif ($percent < 40) {
		print "#ff7777\n";
	} elsif ($percent < 60) {
		print "#ff8888\n";
	} elsif ($percent < 85) {
		print "#ff9999\n";
	}

# EPIGEN_DEL_BLOCK_COLORSCHEME_LIGHT }

# EPIGEN_ADD_BLOCK_COLORSCHEME_LIGHT {

# 	if ($percent < 20) {
# 		print "#A8BB00\n";
# 	} elsif ($percent < 40) {
# 		print "#A89900\n";
# 	} elsif ($percent < 60) {
# 		print "#A86600\n";
# 	} elsif ($percent < 85) {
# 		print "#A83300\n";
# 	}

# EPIGEN_ADD_BLOCK_COLORSCHEME_LIGHT }

	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
