#!/usr/bin/env bash
# This script serves to launch a ros node with gdb attached
# to it in a separate tmux split.
# It can also be launched separately by specifying path to the executable.

if [ $# -lt 1 ]; then
  echo "You must specify path to the executable to be debugged. Ending."
  exit 1;
fi

if [ -z $TMUX ]; then
  echo "You must be in tmux in order to create the split. Ending."
  exit 1;
fi

orig_tty=`tty`
window_number=`tmux display-message -p '#I'`
orig_pane_number=`tmux display-message -p '#P'`

tmux split-window -h
new_pane_number=`tmux display-message -p '#P'`
tmux select-pane -t $window_number.$new_pane_number
new_tty=`tmux display-message -p '#{pane_tty}'`

tmux select-pane -t $window_number.$orig_pane_number
gdb -ex "tty $new_tty" -ex run --args $@
post_cmd="exit"
tmux send-keys -t $window_number.$new_pane_number "$post_cmd"
