#!/usr/bin/env bash
# This script serves to launch a ros node with gdb attached
# to it in a separate tmux split.
# It can also be launched separately by specifying path to the executable.

if [ $# -lt 1 ]; then
  echo "You must specify path to the executable to be debugged. Ending."
  exit 1;
fi

if [ -z $TMUX ]; then
  echo "You must be in tmux in order to create the split. Ending."
  exit 1;
fi

orig_tty=`tty`
pre_cmd="source $HOME/.bashrc; export ROS_NAMESPACE=$ROS_NAMESPACE"
gdb_cmd="gdb -ex 'tty $orig_tty' -ex run --args $@"
cmd="$pre_cmd; $gdb_cmd; exit"
tmux split-window -h "bash -c \"$cmd\""
