name: Docker

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**.jpg'
      - '**.png'
  pull_request:
    branches: [ master ]

  schedule:
    - cron:  '0 0 * * *' # at the end of every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  cancel:

    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_CI: true
      TOKEN: ${{ secrets.DOCKERHUB }}
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch the whole history

      - name: Docker
        run: ./.ci/docker.sh
